[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

[profile.monad]
network = "monad"

[fuzz]
runs = 512

[invariant]
runs = 128
depth = 64
fail_on_revert = false
